In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import tensorflow as tf

In [2]:
ts_c = tf.constant(2,name='ts_c')

In [3]:
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

In [4]:
ts_x = tf.Variable(ts_c+5, name='ts_x')

In [5]:
ts_x

<tf.Variable 'ts_x:0' shape=() dtype=int32_ref>

In [6]:
sess = tf.Session()

In [7]:
init = tf.global_variables_initializer()
sess.run(init)

In [8]:
print('ts_c=', sess.run(ts_c))

ts_c= 2


In [9]:
print('ts_x=', sess.run(ts_x))

ts_x= 7


In [10]:
print('ts_c', ts_c.eval(session=sess))

ts_c 2


In [11]:
print('ts_x', ts_x.eval(session=sess))

ts_x 7


In [12]:
sess.close()

In [13]:
a = tf.constant(2, name='2')
x = tf.Variable(a+5, name='x')
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('a=', sess.run(a))
    print('x=', sess.run(x))

a= 2
x= 7


In [14]:
width = tf.placeholder('int32')
heigh = tf.placeholder('int32')
area = tf.multiply(width, heigh)

In [15]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area=', sess.run(area, feed_dict={width:6, heigh:8}))

area= 48


In [16]:
tf.summary.merge_all()
train_writer = tf.summary.FileWriter('log/area', sess.graph)

In [17]:
ts_X = tf.Variable([0.4, 0.2, 0.4])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[0.4 0.2 0.4]


In [18]:
print(X.shape)

(3,)


In [19]:
ts_X = tf.Variable([[0.4, 0.2, 0.4]])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X = sess.run(ts_X)
    print(X)

[[0.4 0.2 0.4]]


In [20]:
print(X.shape)

(1, 3)


In [21]:
W = tf.Variable([[-0.5, -0.2],
                 [-0.3,  0.4],
                 [-0.5,  0.2]])
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    W_array = sess.run(W)
    print(W_array)

[[-0.5 -0.2]
 [-0.3  0.4]
 [-0.5  0.2]]


In [22]:
print(W_array.shape)

(3, 2)


In [24]:
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([[-0.5, -0.2],
                 [-0.3,  0.4],
                 [-0.5,  0.2]])

XW = tf.matmul(X,W )
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.3  0.4]]


In [28]:
b = tf.Variable([[0.1, 0.2]])
XW = tf.Variable([[-1.3 ,0.4]])
Sum = XW + b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('Sum:')
    print(sess.run(Sum))

Sum:
[[-1.1999999  0.6      ]]


In [30]:
X = tf.Variable([[1., 1., 1.]])
W = tf.Variable([[-0.5, -0.2],
                 [-0.3,  0.4],
                 [-0.5,  0.2]])
b = tf.Variable([[0.1, 0.2]])

XWb = tf.matmul(X,W) + b
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb')
    print(sess.run(XWb))

XWb
[[-1.1999999  0.6      ]]
